language: go
go:
- master
install:
- git clone https://github.com/gohugoio/hugo.git
- cd hugo
- go install --tags extended
- cd -
- rm -rf public 2> /dev/null
- chmod u+x add-hugo-theme.sh
script:
- bash add-hugo-theme.sh
- hugo
after_success:
- cp .travis.yml public
- cd public
- git init
- git config user.name "StevenHugo"
- git config user.email "StevenHugo"
- git add -A
- git commit -m "Update"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/StevenHugo/stevenhugo.github.io.git
  - secure: mTs1QbbE51Bh1gzeYxLWkyiTabgtIabk/h2pKoUWCXmEYY74P1IQ24AMFm529DLYJSvCAZdOXIuIfxHnSM7R/PGR1Gim0sUZfDbRZku9im5V2uq8GasnqHc2W31BFBnM3kEy31YNTIlutP1gsXyckKTEbQ9baFhWv/cdFkODX7mDT5Wv5Crew23pNmz6q6xXO1/H1XWy0OV92y+XJADFlsU4PZ9w8H8dm8CntPtjh3jaR5dFqpOomr60i2n+X7Xy2B3cIoogHMX79uC+oq7QI8cbUBtQjh/8l4k2cvh1S4oKcbM1/gqXPvNqTwDGTWPFKIF/Pe2EuUCtmQY2TcZx3ur6/NCLDzFcqwQmKLhmvy6EPVRt1Q/5Ky1O+K819sqDy0Pc8PdqrxvHLSMAQEyEczi9Kiht0VunhseGvyvAGz7A4vKV8UgEoSRICRNAAGj7C8QQgCnjfLQowHrbvGb2dyp03cJTZW6jOwCTT7AH2J1LbLTbq4O5xVdV1s8bdG88SfgWRD9QYKFfEKXEqL15PGPN2jtDzt7AvaRkVk9ZD97zpCZCxNZzEbP/q5f7DNVx2H/zPtfJW7U7Vk1Z9lNy4OH1QuvtEObxMNu6gtj/hJQPdSEXOG5AfCwhBJt/cFLD5cbpKZcCyJR/7gRT9qfL++cmsjFYe9oRmP2nu6NTc8w=
