language: go

go:
  - master

install:
  - git clone https://github.com/gohugoio/hugo.git
  - cd hugo
  - go install --tags extended
  - cd -
  - rm -rf public 2> /dev/null  # cleanup previous run
  - chmod u+x add-hugo-theme.sh

script:
  - bash add-hugo-theme.sh
  - hugo -d  # generate!

after_success:
  - cp .travis.yml public  # all branches need this file
  - bash deploy.sh # run the deploy script

branches:
  only:
    - master

env:
  global:
    - GIT_DEPLOY_DIR=public # this is the default output dir of Hugo
    - GIT_DEPLOY_BRANCH=master # this is the target branch, replace by gh-pages for Project Pages
    - GIT_DEPLOY_USERNAME="StevenHugo" # dummy name
    - GIT_DEPLOY_EMAIL=stevenhugo # replace by your email
    - secure: Wccb9VyiGc29+OJnvSTLe6qBaTzEYgKRfqv2U+hMnKZEhNEQ72MvcukRwAQ9M7AaEdyyC5xmXKrG1pkkNeTLf3vvIOvInr2LDJ6zzViYXAQh4Q+DZ60SrfASUHMIKvFNNAwM/d6fh9QYIV/WpwnES5ylzMeVT1O47MAspZKzsZjDFSoL0Afldep5kgO1mLJCujwci51yk1dakE0ZlKDVcfvZePLfM60c0npyyZM62zIefZs0Yyo1IGCa3VokFTAeRJm5ht4Ap05KsDsto4hiRzQjLk5eCLz0kMN5YFb0i9DgJM8GS1t1s1t+iSXhyyGXFRxiS1thn8oWHebo67KH+5oNLPJpO/E1I0Wi0LZYc7cfsRnniMBV+4az8eIdKOH72iBdDer7bQ3IoeDKQQgaIekHOB04wajg9efrXLp5Puzk8wcSttl6Pol6jugEvDLPfHTNf8Ngb88v4Zink9Vuic5Fys4HmGvOnFm7wte0Vi0UrZq9ScVy2pU0uQKreH0C8u0XVBhnvbDVHlvz8HGALJgo3h+eL3yvyntzPcKsfyBotmRdVc0laqR98vIiWC0gsyU5/M2PSUNvj33oIb3Oih5wpu4UM0DYsfMiy5ZabphQTn0CDwHNwg269rTqKcpvkOh0wfBJg57rjJxG83ei4qnoEFxSabugmFG0pZWOZ2E=   # replace by the output from travis encrypt done earlier
